### ISSUE TITLE
connection refused on ./gilfoyle serve

### ISSUE THREAD

**Issue by ghost** [dreamvo/gilfoyle#293]
**Description**
I get this error when i try to start with "./gilfoyle serve -p 8080 --config ./gilfoyle.yml" or "./gilfoyle serve":

{"level":"fatal","time":"2021-12-31T13:09:57.985Z","caller":"gilfoyle/serve.go:65","message":"failed creating schema resources","error":"dial tcp [::1]:5432: connect: connection refused","stacktrace":"github.com/dreamvo/gilfoyle/cmd/gilfoyle.glob..func3\n\t/home/runner/work/gilfoyle/gilfoyle/cmd/gilfoyle/serve.go:65\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\ngithub.com/dreamvo/gilfoyle/cmd/gilfoyle.Execute\n\t/home/runner/work/gilfoyle/gilfoyle/cmd/gilfoyle/root.go:45\nmain.main\n\t/home/runner/work/gilfoyle/gilfoyle/cmd/main.go:6\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.6/x64/src/runtime/proc.go:204"}

**Environment**
 - OS: Debian 9.8
 - Gilfoyle version: 0.1.0 commit 23c0da8
 - Go version: 1.13
 - FFmpeg version: 3.2.14-1

**Comment by sundowndev** [comment]
Hi, you have to run a postgres database server in order to run Gilfoyle. It cannot work without PG and rabbitmq. See [DESIGN.md](https://github.com/dreamvo/gilfoyle/blob/master/DESIGN.md#technical-architecture). You can use [this development docker compose file](https://github.com/dreamvo/gilfoyle/blob/master/.support/docker/docker-compose.dev.yml) to easily deploy those locally.

In the meantime, please be aware that this project is still unstable and buggy. I've stopped development to focus on my full time job.

**Comment by DenyHD** [comment]
Hi, i installed all the needed programs, but now it gives my another error:


{"level":"fatal","time":"2022-01-01T16:30:02.798Z","caller":"gilfoyle/serve.go:65","message":"failed creating schema resources","error":"pq: password authentication failed for user \"postgres\"","stacktrace":"github.com/dreamvo/gilfoyle/cmd/gilfoyle.glob..func3\n\t/home/runner/work/gilfoyle/gilfoyle/cmd/gilfoyle/serve.go:65\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\ngithub.com/dreamvo/gilfoyle/cmd/gilfoyle.Execute\n\t/home/runner/work/gilfoyle/gilfoyle/cmd/gilfoyle/root.go:45\nmain.main\n\t/home/runner/work/gilfoyle/gilfoyle/cmd/main.go:6\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.6/x64/src/runtime/proc.go:204"}

I looked for fixes but i don't know why gilfoyle can't conntect with postgres.

**Comment by SarkarKurdish** [comment]
Hey @sundowndev , I've encountered this issue too,

Here is what I've done so far

I have these docker containers up and running
![image](https://user-images.githubusercontent.com/37934074/178815987-f56ea667-2a8a-4674-9e5f-228f3a65fd69.png)

And this is the docker compose config file i've used to create the containers
![image](https://user-images.githubusercontent.com/37934074/178816081-767e1a93-e7b0-44c1-b91e-f4534a3b930d.png)

This is the Docker postgres container output 
![image](https://user-images.githubusercontent.com/37934074/178816272-324395e7-ddae-4002-8148-34f23fc5e4a6.png)

And i've confirmed that the database is up and running and I can connect through PgAdmin just fine
![image](https://user-images.githubusercontent.com/37934074/178816378-e9287e75-2d16-424c-b5a8-6698403055b3.png)

And this is the config for gilfoyle docker image I have
![image](https://user-images.githubusercontent.com/37934074/178816510-936e694e-0bcb-4cf1-a88b-f0502fa5505c.png)

I've set up the compose variable based on the config on the gilfoyl image.
When i try to start the app I've get this error
![image](https://user-images.githubusercontent.com/37934074/178816657-c56f82cc-49bb-49e4-8f5a-1c6e0570f6e9.png)

```
{"level":"info","time":"2022-07-13T19:33:38.242Z","caller":"gilfoyle/serve.go:39","message":"Initializing API server"}
{"level":"info","time":"2022-07-13T19:33:38.242Z","caller":"gilfoyle/serve.go:40","message":"Environment","debug":false}
{"level":"fatal","time":"2022-07-13T19:33:38.243Z","caller":"gilfoyle/serve.go:65","message":"failed creating schema resources","error":"dial tcp 127.0.0.1:5432: connect: connection refused","stacktrace":"github.com/dreamvo/gilfoyle/cmd/gilfoyle.glob..func3\n\t/app/cmd/gilfoyle/serve.go:65\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\ngithub.com/dreamvo/gilfoyle/cmd/gilfoyle.Execute\n\t/app/cmd/gilfoyle/root.go:45\nmain.main\n\t/app/cmd/main.go:6\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"}
```
