### ISSUE TITLE
Docker installation does not work

### ISSUE THREAD

**Issue by SarkarKurdish** [dreamvo/gilfoyle#347]
Hey @sundowndev , I've encountered this issue too,

Here is what I've done so far

I have these docker containers up and running
![image](https://user-images.githubusercontent.com/37934074/178815987-f56ea667-2a8a-4674-9e5f-228f3a65fd69.png)

And this is the docker compose config file i've used to create the containers
![image](https://user-images.githubusercontent.com/37934074/178816081-767e1a93-e7b0-44c1-b91e-f4534a3b930d.png)

This is the Docker postgres container output 
![image](https://user-images.githubusercontent.com/37934074/178816272-324395e7-ddae-4002-8148-34f23fc5e4a6.png)

And i've confirmed that the database is up and running and I can connect through PgAdmin just fine
![image](https://user-images.githubusercontent.com/37934074/178816378-e9287e75-2d16-424c-b5a8-6698403055b3.png)

And this is the config for gilfoyle docker image I have
![image](https://user-images.githubusercontent.com/37934074/178816510-936e694e-0bcb-4cf1-a88b-f0502fa5505c.png)

I've set up the compose variable based on the config on the gilfoyl image.
When i try to start the app I've get this error
![image](https://user-images.githubusercontent.com/37934074/178816657-c56f82cc-49bb-49e4-8f5a-1c6e0570f6e9.png)

```
{"level":"info","time":"2022-07-13T19:33:38.242Z","caller":"gilfoyle/serve.go:39","message":"Initializing API server"}
{"level":"info","time":"2022-07-13T19:33:38.242Z","caller":"gilfoyle/serve.go:40","message":"Environment","debug":false}
{"level":"fatal","time":"2022-07-13T19:33:38.243Z","caller":"gilfoyle/serve.go:65","message":"failed creating schema resources","error":"dial tcp 127.0.0.1:5432: connect: connection refused","stacktrace":"github.com/dreamvo/gilfoyle/cmd/gilfoyle.glob..func3\n\t/app/cmd/gilfoyle/serve.go:65\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\ngithub.com/dreamvo/gilfoyle/cmd/gilfoyle.Execute\n\t/app/cmd/gilfoyle/root.go:45\nmain.main\n\t/app/cmd/main.go:6\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"}
```

_Originally posted by @SarkarKurdish in https://github.com/dreamvo/gilfoyle/issues/293#issuecomment-1183601063_

**Comment by sundowndev** [comment]
Hi, the gilfoyle container is not using the host network : `docker run --rm -it --network host dreamvo/gilfoyle serve -p 8080`

Then you'll have an error about PG not using SSL, disable it with the PGSSLMODE env var : `docker run --rm -it --network host -e PGSSLMODE=disable dreamvo/gilfoyle serve -p 8080`

**Comment by SarkarKurdish** [comment]
Thanks, I ended up installing without docker.
